name: Netcord-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make
        make install
        make install-dev
      
    - name: Build docker image
      run: make docker-build
    
    - name: Lint
      run: make lint

    - name: Test
      run: make test
